#' @title Checks if data is in correct format.
#'
#' @param data the input data. It can be either a list that contains a data frame in .$timeIntensityData or can be a data frame by itself.
#' @param showDetails logical, if TRUE the function will provide an output "check done" if everything is OK. Default is FALSE
#'
#' @description Checks if the input data is appropriate and if it is not, the function converts it into a suitable form. The input data frame should contain two columns named time and intensity related to time variable and intensity variable respectively. If the data frame is in a list its name in the list should be $timeIntensityData.
#' @export
#'
#' @examples
#'
#' # Example 1
#'
#' # generate data frame
#' time <- seq(3, 48, 0.5)
#' intensity <- runif(length(time), 3.0, 7.5)
#' dataInput <- data.frame(time, intensity)
#'
#' # Apply dataCheck_spt function
#' dataOutputVariable <- dataCheck_spt(dataInput)
#'
#' # Example 2
#'
#' # generate data frame
#' time <- seq(3, 48, 0.5)
#' intensity <- runif(length(time), 3.0, 7.5)
#' dataInput <- data.frame(time, intensity)
#'
#' # Normalize Data
#' dataOutput <- normalizeData_spt(dataInput)
#' dataInput2 <- dataOutput
#'
#' # Apply dataCheck_spt function
#' dataOutputVariable2 <- dataCheck_spt(dataInput2)

dataCheck_spt <- function(data, showDetails=TRUE){

  isalist <- (is.list(data) & !is.data.frame(data))

  if(isalist){

    doesitcontainTID <- ("timeIntensityData" %in% names(data))

    if(doesitcontainTID){
      issection_dataframe <- is.data.frame(data$timeIntensityData)

      if(issection_dataframe){
        data_next_check <- data$timeIntensityData
      }

      if(!issection_dataframe){
        stop("the timeIntensityData section should be a data frame")
      }

    }

    if(!doesitcontainTID){
      stop("the list should contain timeIntensityData section")
    }

  }

  if(!isalist){
    isadataframe <- is.data.frame(data)

    if(isadataframe){
      data_next_check <- data
      data2 <- data
      data <- list(timeIntensityData=data2)
    }

    if(!isadataframe){
      stop("It should either be a list or a data frame")
    }
  }

  num_columns <- ncol(data_next_check)
  if(num_columns == 2){
    doescolnamescorrect <- ("time" %in% names(data_next_check) & "intensity" %in% names(data_next_check))

    if(doescolnamescorrect){
      arecolumnsnumeric <- (is.numeric(data_next_check$time) & is.numeric(data_next_check$intensity))

      if(arecolumnsnumeric){
        doesIntensityHaveVariation <- (max(data_next_check$intensity,na.rm = T) -
                                         min(data_next_check$intensity,na.rm = T) > 0)

        if(!doesIntensityHaveVariation){
          warning("min intensity = max intensity i.e intensity do not have variation")
        }

        if(doesIntensityHaveVariation) {
          if(showDetails == FALSE) {print("check done")}
          return(dataCheckVariable <- "pass")
        }

      }

      if(!arecolumnsnumeric){
        stop("The columns should include numbers")
      }

    }

    if(!doescolnamescorrect){
      stop("The column names should be time and intensity")
    }

  }

  if(!num_columns == 2){
    stop("The data frame should contain 2 columns")
  }

}


#' @title Check is data came from the same source.
#'
#' @param dataInput a data frame composed of two columns. One is for time and the other is for intensity. Should be normalized data generated by normalizeData.
#' @param sigmoidalFitVector is the output of sigFit. Default is NULL.
#' @param doubleSigmoidalFitVector is the output of double sigmoidal fit function. Default is NULL.
#'
#' @description Checks if the provided data and models came from same source by looking to ".dataInputName" columns of the inputs.
#' @return Returns TRUE if models can from same source, FALSE otherwise.
#' @export
#'
sameSourceDataCheck_spt <- function(dataInput,
                                    sigmoidalFitVector,
                                    doubleSigmoidalFitVector){

  # do the checks for data input
  # decide if data input is a data frame or a normalized data frame
  isalist <- (is.list(dataInput) & !is.data.frame(dataInput))
  if(isalist){
    sameSourceDataCheck_spt.dataInput=dataInput$dataInputName
  }
  isadataframe <- (is.data.frame(dataInput))
  if(isadataframe){
    sameSourceDataCheck_spt.dataInput <- NA
  }


  # do the checks for sigmoidal fit vector
  # decide if sigmoidal fit is provided or not
  if(is.null(sigmoidalFitVector)){
    sameSourceDataCheck_spt.sigmoidal <- NA
  }
  if(!is.null(sigmoidalFitVector)){
    sameSourceDataCheck_spt.sigmoidal <- sigmoidalFitVector$dataInputName
  }

  # do the checks for double sigmoidal fit vector
  # decide if double sigmoidal fit is provided or not
  if(is.null(doubleSigmoidalFitVector)){
    sameSourceDataCheck_spt.doublesigmoidal <- NA
  }
  if(!is.null(doubleSigmoidalFitVector)){
    sameSourceDataCheck_spt.doublesigmoidal <- doubleSigmoidalFitVector$dataInputName
  }

  # make decision
  sameSourceDataCheckVector <- c(dataInput = sameSourceDataCheck_spt.dataInput,
                                 sigmoidal = sameSourceDataCheck_spt.sigmoidal,
                                 doublesigmoidal = sameSourceDataCheck_spt.doublesigmoidal)
  sameSourceDataCheckVector <- sameSourceDataCheckVector[!is.na(sameSourceDataCheckVector)]

  if(length(sameSourceDataCheckVector) != 0){
    if(!all(sameSourceDataCheckVector[1] == sameSourceDataCheckVector)){
      print(sameSourceDataCheckVector)
      stop("all data need to come from same source!")
    }
  }
}
